# Generated by Django 3.0.3 on 2020-02-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCapitalFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(default='Thor', max_length=255)),
                ('bet', models.FloatField(default=0.0, help_text='有效总投注')),
                ('rebate', models.FloatField(default=0.0, help_text='返水')),
                ('sports', models.FloatField(default=0.0, help_text='体育赛事')),
                ('live', models.FloatField(default=0.0, help_text='视讯直播')),
                ('casino', models.FloatField(default=0.0, help_text='老虎机')),
                ('lottery', models.FloatField(default=0.0, help_text='彩票')),
                ('fish', models.FloatField(default=0.0, help_text='捕鱼机')),
                ('card', models.FloatField(default=0.0, help_text='棋牌')),
                ('update', models.DateField(auto_now=True)),
                ('date', models.DateField(default='2020-02-06')),
            ],
        ),
        migrations.CreateModel(
            name='IntegralMallHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='用户名', max_length=255)),
                ('integral_mall_level', models.CharField(choices=[('0', '普通会员'), ('1', '黄金会员'), ('2', '铂金会员'), ('3', '钻石会员'), ('4', '至尊会员'), ('5', '王者会员'), ('6', '特邀会员')], default='0', help_text='商城等级', max_length=255)),
                ('current_level_up_money', models.IntegerField(default=0, help_text='当月晋级礼金')),
                ('current_month_discount', models.FloatField(default=1.0, help_text='折扣比例')),
                ('current_month_date', models.DateField(help_text='记录月份')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(default='Thor', max_length=255)),
                ('user_level', models.IntegerField(default=0, help_text='官网VIP等级')),
            ],
        ),
    ]
