# Generated by Django 3.0.3 on 2020-02-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='month_capital_flow',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='month_error_flow',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
