# Generated by Django 3.0.3 on 2020-02-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_auto_20200206_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integralmallhistory',
            name='integral_mall_level',
            field=models.IntegerField(choices=[(0, '普通会员'), (1, '黄金会员'), (2, '铂金会员'), (3, '钻石会员'), (4, '至尊会员'), (5, '王者会员'), (6, '特邀会员')], default=0, help_text='商城等级'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_level',
            field=models.IntegerField(choices=[(0, '普通会员'), (1, '黄金会员'), (2, '铂金会员'), (3, '钻石会员'), (4, '至尊会员'), (5, '王者会员'), (6, '过渡层')], default=0),
        ),
    ]
